# [[plugins]]
# repo = 'kristijanhusak/vim-hybrid-material'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = "release"
hook_add = """
source ~/dotfiles/nvim/coc.rc.vim
"""

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = """
source ~/dotfiles/nvim/defx.rc.vim
"""

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
mergerd = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'npm install'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'cocopon/iceberg.vim'

#[[plugins]]
#repo = 'neovim/nvim-lspconfig'
#
#[[plugins]]
#repo = 'mattn/vim-lsp-settings'
#
#[[plugins]]
#repo = 'glepnir/lspsaga.nvim'

[[plugins]]
repo = 'skanehira/preview-markdown.vim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'romgrk/barbar.nvim'
depends = 'nvim-web-devicons'

