[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # カラースキーマ
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = "release"
hook_add = """
source ~/dotfiles/nvim/coc.rc.vim
"""

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = """
source ~/dotfiles/nvim/defx.rc.vim
"""

[[plugins]]
repo = 'kristijanhusak/defx-icons'


[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

