[memory_usage]
disabled = false
threshold = 90
symbol = " "
style = "bold dimmed green"

[gcloud]
format = 'on [$symbol\($project\)]($style) '

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = ''
ahead = ''
behind = ''
diverged = ''
up_to_date = '✓'
untracked = ''
stashed = ''
modified = '🔥'
staged = ''
renamed = ''
deleted = ''
